# ── Docker Networks ──────────────────────────────────────────────────────────
networks:
  client-side:
    driver:
      bridge
  server-side:
    driver:
      bridge

# ── Docker Services ──────────────────────────────────────────────────────────
services:
  # ── Frontend (React) ─────────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - client-side
# Uncomment to test frontend only (as a single service)
    # ports:
    #   - "5173:5173"

  # ── Backend (Nest.js) ────────────────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - client-side
      - server-side
    secrets:
      - backend_pw
      - jwt_secret
      - database_url
    depends_on:
      db:
        condition: service_healthy
# Uncomment temporarily to access Prisma Studio from host
    # ports:
    #  - "5555:5555"

# Uncomment to test backend only (as a single service)
    # ports:
    #   - "3000:3000"


  # ── Reverse Proxy (Nginx) ────────────────────────────────────────
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    networks:
      - client-side
    depends_on:
      - frontend
      - backend

  # ── Database (Postgres) ──────────────────────────────────────────
  db:
    image: postgres:${POSTGRES_VERSION:-18-alpine} #fallback to 18-alpine if var not set
    networks:
      - server-side
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_pw
      - BACKEND_USER=${BACKEND_USER}
      - BACKEND_PW_FILE=/run/secrets/backend_pw
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
    secrets:
      - backend_pw
      - postgres_root_pw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

# ── Docker Volumes ──────────────────────────────────────────────────────────
volumes:
  postgres_data:

# ── Docker Secrets ──────────────────────────────────────────────────────────
secrets:
  backend_pw:
    file: ./secrets/backend_pw.txt
  postgres_root_pw:
    file: ./secrets/postgres_root_pw.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  database_url:
    file: ./secrets/database_url.txt
