#!/bin/bash
set -e

BACKEND_PASSWORD=$(cat /run/secrets/backend_pw)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${BACKEND_USER} WITH PASSWORD '${BACKEND_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${BACKEND_USER};
    
    -- Connect to the database
    \c ${POSTGRES_DB}
    
    -- Schema-level privileges
    GRANT USAGE, CREATE ON SCHEMA public TO ${BACKEND_USER};
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${BACKEND_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${BACKEND_USER};
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${BACKEND_USER};
    
    -- Default privileges for future objects (Needed for ORM solution)
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${BACKEND_USER};
EOSQL