# ── PROD Nginx Config ────────────────────────────────────────────────────────

# ── required by nginx, left empty to use default setttings ───────────────────
events {}

# ── HTTP → HTTPS Redirect ────────────────────────────────────────────────────
http {
	server {
		listen 80;
		server_name _;
		
		# Redirect all HTTP traffic to HTTPS
        # Note: :8443 is explicit because host port is non-standard (8443:443)
        # If host port changes in compose.prod.yaml, update this too
		return 301 https://$host:8443$request_uri;
	}


# ── Main Server (HTTPS) ──────────────────────────────────────────────────────
	server {
		listen 443 ssl;
		server_name _;
		
		
	# ── TLS Certificate ──────────────────────────────────────────────────────
        ssl_certificate     /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;	
	
	
	# ── Frontend ─────────────────────────────────────────────────────────────
		location / {
			proxy_pass http://frontend:80;

		# ── Pass Host and real client info ───────────────────────────────────
			proxy_set_header Host $host;			
			
			# ── Pass real client info ────────────────────────────────────────
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
   			proxy_set_header X-Forwarded-Proto $scheme;						# HTTP or HTTPS
		}
		
		
	# ── Backend API ──────────────────────────────────────────────────────────
		# ── forwards all requests starting with `/api/` to backend ───────────
		location /api/ {
			
			# ── remove `/api/` from URI, forward to NestJS ───────────────────
			rewrite ^/api/(.*) /$1 break;
			proxy_pass http://backend:3000;
			
			# ── Pass real client info  ───────────────────────────────────────
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
			proxy_set_header X-Forwarded-Proto $scheme;						# HTTP or HTTPS
		}



	# ── Socket.IO ────────────────────────────────────────────────────────────
		location /socket.io/ {
			proxy_pass http://backend:3000;

			# ── Allow WebSocket upgrade for real-time communication ──────────
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			# ── Pass real client info ────────────────────────────────────────
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
			proxy_set_header X-Forwarded-Proto $scheme;					# HTTP or HTTPS

			# ── Max silence gap before Nginx drops connection ────────────────
			# ── ex: wait time to find game, time between moves, spectator ────
			proxy_read_timeout 3600; # seconds
		}
	}
}