# required by nginx, left empty for now
events {}

http {
	server {
		listen 80;
		
		# forward all requests to frontend
		location / {
			proxy_pass http://frontend:5173;

			# Vite Host security bypass for DEV
			proxy_set_header Host localhost;			# Set Host to localhost so Vite doesn't block request
			proxy_set_header X-Real-IP $remote_addr;	# Pass the browser's IP address through instead of Nginx's IP
   			proxy_set_header X-Forwarded-Proto $scheme;	# track whether HTTP or HTTPS protocol
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # track the IP Address path (All IPs the request went through)
			
			# Allow WebSockets to pass through (for hot reload)
    		proxy_http_version 1.1;
    		proxy_set_header Upgrade $http_upgrade;
   			proxy_set_header Connection "upgrade";
		}
		
		# forward all requests starting with `/api/` to backend
		location /api/ {
			
			# remove `/api/` from URI
			rewrite ^/api/(.*) /$1 break;
			proxy_pass http://backend:3000;
			proxy_set_header Host localhost;
			proxy_set_header X-Real-IP $remote_addr;
		}

		# forward all requests related to Socket.IO to backend
		location /socket.io/ {
			proxy_pass http://backend:3000;

			# allow WebSocket upgrade for real-time communication
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			# set Host to localhost for consistency with current dev setup
			proxy_set_header Host localhost;

			# Pass the browser's IP address through instead of Nginx's IP
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}