# required by nginx, left empty for now
events {}

http {
	server {
		listen 80;
		
		# forward all requests to frontend
		location / {
			proxy_pass http://frontend:5173;

			# set Host to localhost so Vite doesn't block request (setup for testing purposes in Dev mode)
			# needs more research for later down the road
			proxy_set_header Host localhost;

			# Pass the browser's IP address through instead of Nginx's IP
			proxy_set_header X-Real-IP $remote_addr;
		}
		
		# forward all requests starting with `/api/` to backend
		location /api/ {
			
			# remove `/api/` from URI
			rewrite ^/api/(.*) /$1 break;
			proxy_pass http://backend:3000;
			proxy_set_header Host localhost;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}