# ── DEV Nginx Config ─────────────────────────────────────────────────────────

# ── required by nginx, left empty to use default setttings ───────────────────
events {}

http {
	server {
		listen 80;
		server_name _;
		
	# ── Frontend (Vite dev server) ───────────────────────────────────────────
		location / {
			proxy_pass http://frontend:5173;

		# ── Vite Host security bypass for DEV ────────────────────────────────
			# ── Set Host to localhost so Vite doesn't block request ──────────
			proxy_set_header Host localhost;			
			
			# ── Pass real client info instead of Nginx's info ────────────────
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
   			proxy_set_header X-Forwarded-Proto $scheme;						# HTTP or HTTPS
			
			# ── Allow WebSockets to pass through (for hot reload) ────────────
    		proxy_http_version 1.1;
    		proxy_set_header Upgrade $http_upgrade;
   			proxy_set_header Connection "upgrade";
		}
		
		
	# ── Backend API ──────────────────────────────────────────────────────────
		# ── forwards all requests starting with `/api/` to backend ───────────
		location /api/ {
			
			# ── remove `/api/` from URI, forward to NestJS ───────────────────
			rewrite ^/api/(.*) /$1 break;
			proxy_pass http://backend:3000;
			
			# ── Pass real client info instead of Nginx's info ────────────────
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
			proxy_set_header X-Forwarded-Proto $scheme;					# HTTP or HTTPS
		}



	# ── Socket.IO ────────────────────────────────────────────────────────────
		location /socket.io/ {
			proxy_pass http://backend:3000;

			# ── Allow WebSocket upgrade for real-time communication ──────────
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			# ── Pass real client info instead of Nginx's info ────────────────
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
			proxy_set_header X-Forwarded-Proto $scheme;					# HTTP or HTTPS

			# ── Max silence gap before Nginx drops connection ────────────────
			# ── ex: wait time to find game, time between moves, spectator ────
			proxy_read_timeout 3600; # seconds
		}

		# forward all requests related to Socket.IO to backend
		location /socket.io/ {
			proxy_pass http://backend:3000;

			# allow WebSocket upgrade for real-time communication
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			# set Host to localhost for consistency with current dev setup
			proxy_set_header Host localhost;

			# Pass the browser's IP address through instead of Nginx's IP
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}